### ISSUE TITLE
No Neo4j Server 😠 

### ISSUE THREAD

**Issue by iliaamiri** [IGAQ/NestServer#15]
We need a valid connection string for our Neo4j database.

**Comment by iantelli** [comment]
I just checked and can confirm this is an ongoing issue, hopefully it will be fixed soon by our database manager.

**Comment by iliaamiri** [comment]
Thank you Ian. I have discussed this matter with our database admin. We resolved the issue.
I will close this.

**Comment by 23o4i7** [comment]
idk i gave u db auth

**Comment by iliaamiri** [comment]
Yes. I well acknowledge that. I appreciate the effort and time.
