### ISSUE TITLE
Neo4J Seeding Duplicate Data

### ISSUE THREAD

**Issue by iantelli** [IGAQ/NestServer#56]
### Description

Whenever running the jest script, my local database gets seeded with duplicate sexuality nodes over and over. This is affecting my tests speed and populating my local database with useless nodes.

**Comment by 23o4i7** [comment]
delete your local db

**Comment by iliaamiri** [comment]
please read our GitHub issue [style guide](https://www.youtube.com/watch?v=dQw4w9WgXcQ) before posting an issue.
Thank you

**Comment by iliaamiri** [comment]
fixed

**Comment by iliaamiri** [comment]
fixedd
